
#spring:
#  datasource:
#    url: jdbc:mysql://localhost:3306/cognitodb
#    username: root
#    password: Brpl@123
#    
#    
#  jpa:
#    hibernate:
#      ddl-auto: update
#    
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect

#spring:
#  security:
#    oauth2:
#      client:
#        registration:
#          cognito:
#            client-id: ""
#            client-secret: ""
#        provider:
#          cognito: 
#            issuer-uri: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_w5BD2MI1A"
            

#spring.security.oauth2.client.registration.cognito.client-id = {your-app-client-id}
#spring.security.oauth2.client.registration.cognito.client-secret = {your-app-client-secret}
#spring.security.oauth2.client.registration.cognito.scope = openid
#spring.security.oauth2.client.registration.cognito.redirect-uri = http://localhost:8080/login/oauth2/code/cognito
#spring.security.oauth2.client.registration.cognito.clientName = {your-app-client-name}
#spring.security.oauth2.client.registration.cognito.authorization-grant-type=authorization_code
#spring.security.oauth2.client.provider.cognito.issuerUri = https://cognito-idp.{your-user-pool-region}.amazonaws.com/{user-pool-id}            
                        

spring:
  security:
    oauth2:
      client:
        registration:
          cognito:
            client-id: ""
            client-secret: ""
            scope: openid, email, profile
            redirect-uri: "http://localhost:8080/login/oauth2/code/cognito"
            authorization-grant-type: authorization_code
        provider:
          cognito:
            issuer-uri: "https://cognito-idp.us-east-1.amazonaws.com/us-east-1_w5BD2MI1A"   


cognito:
  userPoolId: us-east-1_w5BD2MI1A
                      

aws:
  cognito: 
    logoutUrl: "https://brpldomain01.auth.us-east-1.amazoncognito.com/logout"                    
    logout:
      success:
        redirectUrl: "http://localhost:8080/logout"        
  accessKey: ""
  secretKey: ""       
  region: "us-east-1"          
            
            
logging:
  level:
    org:
      springframework:
        security: DEBUG            
            